// ============================================================
// BIS SAARTHI AI / BISYNAPSE — COMPREHENSIVE SEED DATASET
// Contains verified BIS standards data & clearly labeled DEMO records
// ============================================================

const standardsData = [
  {
    standard_number: 'IS 302 (Part 2/Sec 3): 2007',
    title: 'Safety of Household and Similar Electrical Appliances - Particular Requirements - Electric Kettles',
    category: 'Electrical & Electronics',
    sector: 'Consumer Electronics & Household Goods',
    description: 'Specifies electrical insulation, heating safety, earthing provisions, and automatic cutoff parameters for electric kettles and boiling appliances.',
    scope: 'Applicable to single-phase household electric kettles, jugs, and liquid heating vessels rated up to 250V.',
    edition: '2.1',
    publication_date: '2007-06-15',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/index.php/standards/find-a-standard/',
    source: 'Bureau of Indian Standards',
    source_type: 'Quality Control Order (QCO)',
    key_requirements: ['High-voltage insulation breakdown withstand test (1500V)', 'Automatic dry-boil thermal safety cutoff', 'Double-insulated internal wiring', 'IPX4 moisture protection against liquid spillage'],
    testing_required: ['Dielectric Strength Test', 'Thermal Cutout Reliability Test', 'Operating Temperature Leakage Current', 'Mechanical Switch Endurance (10,000 cycles)'],
    searchable_text: 'IS 302 2 3 electric kettle heater household electrical appliance safety boil cutoff heating element 250v',
    is_demo: false,
  },
  {
    standard_number: 'IS 13252 (Part 1): 2010',
    title: 'Information Technology Equipment - Safety - General Requirements',
    category: 'Information Technology',
    sector: 'Electronics & IT Goods',
    description: 'Specifies safety standards to prevent electrical shock, fire hazard, energy hazard, and mechanical hazards from IT and office equipment.',
    scope: 'Applicable to personal computers, laptops, mobile phone chargers, power adapters, data display monitors, and network equipment.',
    edition: '1.2',
    publication_date: '2010-11-20',
    status: 'Mandatory (QCO)',
    scheme: 'Compulsory Registration Scheme (CRS — Scheme II)',
    document_url: 'https://www.crsbis.in/BIS/',
    source: 'MeitY / Bureau of Indian Standards',
    source_type: 'Electronics & IT Goods Mandatory Order',
    key_requirements: ['Creepage distance and electrical clearance compliance', 'Enclosure flammability rating V-0 or V-1', 'Protection against electric shock under fault conditions'],
    testing_required: ['Input Power Rating Measurement', 'Max Operating Thermal Rise Test', 'Ball Pressure Enclosure Stress Test', 'Earth Continuity Test'],
    searchable_text: 'IS 13252 IT equipment laptop charger adapter mobile power supply information technology safety crs scheme 2',
    is_demo: false,
  },
  {
    standard_number: 'IS 1417: 2016',
    title: 'Gold and Gold Alloys, Jewellery/Artefacts - Fineness and Marking - Specification',
    category: 'Jewellery & Precious Metals',
    sector: 'Consumer Goods & Precious Metals',
    description: 'Defines 6 purity grades for gold jewellery (24K, 23K, 22K, 20K, 18K, 14K) and mandates laser engraving of the BIS Hallmark and 6-digit HUID code.',
    scope: 'Mandatory for all gold jewellery and gold artefacts sold across mandatory hallmarking districts in India.',
    edition: '5.0',
    publication_date: '2016-04-10',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Hallmarking Scheme (Scheme IV)',
    document_url: 'https://www.bis.gov.in/hallmarking-2/',
    source: 'Bureau of Indian Standards',
    source_type: 'Hallmarking Quality Control Order',
    key_requirements: ['Assaying and verification at recognized AHC centres', 'Laser etching of BIS Triangular mark, purity (e.g. 22K916), and unique 6-digit HUID', 'Mandatory registration of jewellers on ManakOnline'],
    testing_required: ['Fire Assay (Cupellation Method IS 1418)', 'X-Ray Fluorescence (XRF) Non-Destructive Screening'],
    searchable_text: 'IS 1417 gold jewellery hallmark huid fineness purity 916 22k 750 18k 585 14k assaying ahc scheme 4',
    is_demo: false,
  },
  {
    standard_number: 'IS 14286 / IEC 61215: 2010',
    title: 'Crystalline Silicon Terrestrial Photovoltaic (PV) Modules - Design Qualification and Type Approval',
    category: 'Solar & Renewable Energy',
    sector: 'Renewable Energy & Power',
    description: 'Specifies testing parameters to verify electrical and thermal stability of silicon solar PV modules for outdoor terrestrial applications.',
    scope: 'Covers monocrystalline and polycrystalline silicon solar photovoltaic modules deployed in residential, commercial, and utility installations.',
    edition: '2.0',
    publication_date: '2010-08-12',
    status: 'Mandatory (QCO)',
    scheme: 'Compulsory Registration Scheme (CRS — Scheme II)',
    document_url: 'https://www.crsbis.in/BIS/',
    source: 'Ministry of New and Renewable Energy (MNRE) / BIS',
    source_type: 'Solar Photovoltaics Mandatory Order',
    key_requirements: ['Thermal cycling endurance test (-40 deg C to +85 deg C)', 'Damp heat aging test (85 deg C / 85% RH for 1000 hours)', 'Mechanical load test under 2400 Pa load'],
    testing_required: ['Visual Inspection & IV Curve Characterization', 'Wet Insulation Leakage Current Test', 'Hail Impact & Mechanical Snow Load Test'],
    searchable_text: 'IS 14286 solar photovoltaic module pv panel solar energy renewable mnre crs silicon',
    is_demo: false,
  },
  {
    standard_number: 'IS 15410: 2003',
    title: 'Packaged Natural Mineral Water - Specification',
    category: 'Food & Agriculture',
    sector: 'Food Safety & Beverages',
    description: 'Specifies microbiological purity limits, mineral concentration tolerances, chemical parameters, and packaging standards for natural mineral water.',
    scope: 'Mandatory for commercial bottling facilities and packaged natural mineral water processors in India.',
    edition: '1.3',
    publication_date: '2003-05-18',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'FSSAI / Bureau of Indian Standards',
    source_type: 'Mandatory ISI Mark Order',
    key_requirements: ['Zero detectable E. coli, Coliforms, and faecal Streptococci per 250ml', 'TDS range strictly bounded between 150 to 700 mg/L', 'Food-grade virgin PET or glass container with tamper-evident seal'],
    testing_required: ['Microbiological Incubation & Colony Count', 'ICP-MS Heavy Metal Spectrometry', 'Organoleptic Taste & Odour Assessment'],
    searchable_text: 'IS 15410 packaged natural mineral water drinking water beverage food agriculture isi mark fssai',
    is_demo: false,
  },
  {
    standard_number: 'IS 1786: 2008',
    title: 'High Strength Deformed Steel Bars and Wires for Concrete Reinforcement - Specification',
    category: 'Construction & Civil',
    sector: 'Metals & Structural Engineering',
    description: 'Covers physical, mechanical, and chemical properties of high strength deformed TMT steel rebar for civil concrete reinforcement.',
    scope: 'Covers steel grades Fe 415, Fe 415D, Fe 500, Fe 500D, Fe 550, Fe 550D, and Fe 600 for earthquake-resistant infrastructure.',
    edition: '4.2',
    publication_date: '2008-03-30',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'Ministry of Steel / BIS',
    source_type: 'Steel and Steel Products QCO',
    key_requirements: ['Yield stress and 0.2% proof stress compliance', 'Mandatory bend and 180-deg reverse re-bend ductility without fracture', 'Maximum Sulphur and Phosphorus content capped at 0.040%'],
    testing_required: ['Tensile & Yield Strength Universal Testing (UTM)', 'Bend & Re-bend Ductility Test', 'Optical Emission Spectrometry (OES) Chemical Analysis'],
    searchable_text: 'IS 1786 tmt steel bar rebar concrete reinforcement construction civil engineering fe 500d isi mark',
    is_demo: false,
  },
  {
    standard_number: 'IS 694: 2010',
    title: 'PVC Insulated Cables for Working Voltages up to and Including 1100 V - Specification',
    category: 'Electrical & Electronics',
    sector: 'Cables, Wires & Electrical Safety',
    description: 'Specifies conductor resistance, insulation thickness, thermal aging resistance, and flame retardancy for domestic and commercial PVC electrical cables.',
    scope: 'Covers single-core, multi-core, flexible and rigid copper/aluminum conductor cables rated up to 1.1 kV.',
    edition: '4.0',
    publication_date: '2010-09-14',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'Bureau of Indian Standards',
    source_type: 'Electrical Cables QCO',
    key_requirements: ['Conductor DC resistance under IS 8130 limits', 'High voltage spark testing during extrusion', 'Oxygen index minimum 29% for Flame Retardant (FR) grade'],
    testing_required: ['Conductor Resistance Measurement', 'Tensile Strength & Elongation of PVC Insulation', 'Flammability Bunsen Burner Test'],
    searchable_text: 'IS 694 pvc insulated cable copper wire electrical wiring building wire 1100v isi mark',
    is_demo: false,
  },
  {
    standard_number: 'IS 1293: 2019',
    title: 'Plugs and Socket-Outlets for Domestic and Similar Purposes - Specification',
    category: 'Electrical & Electronics',
    sector: 'Electrical Accessories',
    description: 'Defines dimensions, shutter safety mechanisms, thermal endurance, and contact resistance for 6A, 16A, and 25A 3-pin plugs and socket outlets.',
    scope: 'Mandatory for all domestic 3-pin electrical plugs, socket outlets, multi-plugs, and extension cords manufactured or sold in India.',
    edition: '4.0',
    publication_date: '2019-07-25',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'DPIIT / BIS',
    source_type: 'Electrical Accessories QCO',
    key_requirements: ['Mandatory child safety shutters on socket phase and neutral slots', 'Earth pin engagement occurs before live pin engagement', 'Temperature rise at terminals <= 45K at full rated current'],
    testing_required: ['Normal Operation Endurance (10,000 insertions)', 'Temperature Rise Test', 'Glow-Wire Flammability Test at 850 deg C'],
    searchable_text: 'IS 1293 plug socket outlet 3 pin 6a 16a electrical accessory switchboard isi mark',
    is_demo: false,
  },
  {
    standard_number: 'IS 4151: 2020',
    title: 'Protective Helmets for Riders of Two-Wheeled Motor Vehicles - Specification',
    category: 'Safety & Automotive',
    sector: 'Road Safety & Automotive Components',
    description: 'Specifies impact absorption energy thresholds, penetration resistance, chin strap retention strength, and peripheral vision angles for two-wheeler motorcycle helmets.',
    scope: 'Mandatory for all protective helmets for riders of two-wheeled motor vehicles in India.',
    edition: '5.0',
    publication_date: '2020-09-01',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'Ministry of Road Transport and Highways (MoRTH) / BIS',
    source_type: 'Protective Helmets Mandatory QCO',
    key_requirements: ['Impact absorption peak deceleration < 300g onto flat and hemispherical anvils', 'Max weight of helmet capped at 1.2 kg', 'Retention system dynamic elongation <= 35 mm under 1 kN load'],
    testing_required: ['Impact Attenuation Drop Test', 'Rigidity and Penetration Conical Impactor Test', 'Chin Strap Micro-Slip and Release Force Test'],
    searchable_text: 'IS 4151 motorcycle helmet protective headgear two wheeler safety morth isi mark',
    is_demo: false,
  },
  {
    standard_number: 'IS 9873 (Part 1): 2019',
    title: 'Safety of Toys - Part 1: Mechanical and Physical Properties',
    category: 'Consumer Products & Toys',
    sector: 'Children Safety & Toys',
    description: 'Establishes safety requirements regarding sharp edges, points, small parts ingestion hazards, sound pressure limits, and projectile safety in toys.',
    scope: 'Mandatory for all toys manufactured or imported into India intended for children up to 14 years of age.',
    edition: '3.0',
    publication_date: '2019-12-10',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'DPIIT / Bureau of Indian Standards',
    source_type: 'Toys Quality Control Order',
    key_requirements: ['Zero detachable small parts for toys intended for children under 36 months', 'Acoustic emission capped under 85 dB for close-to-ear toys', 'Heavy metal element migration (Lead, Cadmium, Arsenic) bounded under Part 3 limits'],
    testing_required: ['Drop Test onto Steel Plate (5 drops from 850 mm)', 'Small Parts Cylinder Ingestion Test', 'Torque and Tension Pull Test (90N)'],
    searchable_text: 'IS 9873 toy safety children kids mechanical physical sharp edges lead isi mark dpiit',
    is_demo: false,
  },
  {
    standard_number: 'IS 16046 (Part 2): 2018 / IEC 62133-2: 2017',
    title: 'Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes - Lithium System',
    category: 'Electrical & Electronics',
    sector: 'Energy Storage & Portable Electronics',
    description: 'Specifies safety requirements for portable secondary lithium cells and battery packs utilized in smartphones, tablets, wearable devices, and electric mobility tools.',
    scope: 'Mandatory under CRS for lithium-ion and lithium polymer cells and battery packs.',
    edition: '2.0',
    publication_date: '2018-06-25',
    status: 'Mandatory (QCO)',
    scheme: 'Compulsory Registration Scheme (CRS — Scheme II)',
    document_url: 'https://www.crsbis.in/BIS/',
    source: 'MeitY / Bureau of Indian Standards',
    source_type: 'Electronics & IT Goods Mandatory Order',
    key_requirements: ['Overcharge safety protection circuit verification', 'External short circuit test without explosion or flame at 55 deg C', 'Thermal abuse test at 130 deg C for 10 minutes'],
    testing_required: ['Continuous Charging at Constant Voltage', 'Free Fall Drop Test', 'Crush and Impact Resistance Mechanical Test'],
    searchable_text: 'IS 16046 lithium battery cell li-ion power bank mobile smartphone battery crs scheme 2',
    is_demo: false,
  },
  {
    standard_number: 'IS 269: 2015',
    title: 'Ordinary Portland Cement - Specification',
    category: 'Construction & Civil',
    sector: 'Building Materials & Civil Construction',
    description: 'Specifies chemical composition, fineness, setting time, and compressive strength requirements for 33, 43, and 53 grade Ordinary Portland Cement (OPC).',
    scope: 'Mandatory for all cement manufacturers and suppliers operating in India.',
    edition: '6.0',
    publication_date: '2015-05-15',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'DPIIT / Bureau of Indian Standards',
    source_type: 'Cement Quality Control Order',
    key_requirements: ['Minimum 28-day compressive strength of 53 MPa for OPC 53 grade', 'Initial setting time >= 30 minutes; final setting time <= 600 minutes', 'Loss on ignition (LOI) <= 5.0% by mass'],
    testing_required: ['Vicat Needle Setting Time Test', 'Mortar Cube Compressive Strength Machine Test', 'Le-Chatelier Autoclave Soundness Test'],
    searchable_text: 'IS 269 ordinary portland cement opc 53 43 cement concrete construction civil building isi mark',
    is_demo: false,
  },
  {
    standard_number: 'IS 1374: 2007',
    title: 'Poultry Feeds - Specification',
    category: 'Agriculture & Food',
    sector: 'Animal Feeds & Agriculture',
    description: 'Defines nutritional parameters, crude protein limits, metabolizable energy, moisture content, and aflatoxin contamination limits for poultry feed.',
    scope: 'Covers starter, grower, layer, and broiler feeds across Indian commercial poultry operations.',
    edition: '5.0',
    publication_date: '2007-04-12',
    status: 'Voluntary / Quality Mark',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'Bureau of Indian Standards',
    source_type: 'Food & Agriculture Division',
    key_requirements: ['Crude protein minimum 20.0% by mass for broiler starter', 'Moisture content <= 11.0% to prevent fungal growth', 'Total Aflatoxin B1 capped under 20 ppb (parts per billion)'],
    testing_required: ['Kjeldahl Nitrogen Crude Protein Assay', 'ELISA / HPLC Aflatoxin Quantification', 'Crude Fibre and Total Ash Analysis'],
    searchable_text: 'IS 1374 poultry feed broiler layer chicken feed agriculture livestock animal nutrition',
    is_demo: false,
  },
  {
    standard_number: 'IS 15652: 2006',
    title: 'Insulating Mats for Electrical Purposes - Specification',
    category: 'Safety & Electrical',
    sector: 'Industrial Safety & Switchgear',
    description: 'Specifies electrical resistance, tensile strength, puncture resistance, and flame retardancy for elastomer insulating floor mats in high voltage substations.',
    scope: 'Mandatory in high-voltage industrial sub-stations and power distribution control panels operating up to 33 kV AC.',
    edition: '2.0',
    publication_date: '2006-11-20',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'Central Electricity Authority / BIS',
    source_type: 'Industrial Safety Standards',
    key_requirements: ['Dielectric withstand voltage up to 45 kV proof test without breakdown', 'Insulation resistance >= 10^6 Mega-Ohms', 'Zero halogen emission and self-extinguishing flame characteristic'],
    testing_required: ['Voltage Withstand Breakdown Chamber Test', 'Tensile and Elongation Stress Test', 'Oil and Acid Chemical Immersion Resistance'],
    searchable_text: 'IS 15652 insulating mat rubber mat electrical safety substation high voltage 33kv switchgear',
    is_demo: false,
  },
  {
    standard_number: 'IS 14534: 1998',
    title: 'Guidelines for Recovery and Recycling of Plastics Wastes',
    category: 'Chemicals & Environment',
    sector: 'Plastics & Waste Management',
    description: 'Provides standardized resin identification codes (Codes 1 to 7: PET, HDPE, PVC, LDPE, PP, PS, OTHER) and processing guidelines for plastic recycling.',
    scope: 'Applicable to plastic polymer manufacturers, packaging converters, and recycling entities across India.',
    edition: '1.0',
    publication_date: '1998-08-10',
    status: 'Mandatory (Plastic Waste Rules)',
    scheme: 'BIS Environmental Guidance / Standard',
    document_url: 'https://www.bis.gov.in/',
    source: 'Ministry of Environment, Forest and Climate Change (MoEFCC) / BIS',
    source_type: 'Environmental Quality Standard',
    key_requirements: ['Mandatory embossed recycling symbol with polymer number on rigid plastic containers', 'Classification criteria for post-consumer vs post-industrial regrind'],
    testing_required: ['FTIR Polymer Spectroscopy Identification', 'Melt Flow Index (MFI) Differential Scanning Calorimetry'],
    searchable_text: 'IS 14534 plastics recycling resin identification pet hdpe pp pvc waste management environment',
    is_demo: false,
  },
  {
    standard_number: 'IS 16102 (Part 1): 2012',
    title: 'Self-Ballasted LED Lamps for General Lighting Services - Part 1: Safety Requirements',
    category: 'Electrical & Electronics',
    sector: 'Lighting & Energy Efficiency',
    description: 'Specifies safety, insulation resistance, fault condition protection, and creepage distances for consumer self-ballasted LED retrofit bulbs.',
    scope: 'Mandatory for all consumer domestic LED bulbs, batten lights, and integrated LED fixtures.',
    edition: '1.0',
    publication_date: '2012-07-15',
    status: 'Mandatory (QCO)',
    scheme: 'Compulsory Registration Scheme (CRS — Scheme II)',
    document_url: 'https://www.crsbis.in/BIS/',
    source: 'MeitY / Bureau of Indian Standards',
    source_type: 'Electronics & IT Goods Mandatory Order',
    key_requirements: ['Lamp cap torque endurance test under IS 16102 Part 1', 'Insulation resistance > 4 Mega-Ohms after 48-hour humidity chamber', 'Photobiological eye safety risk group RG0 or RG1 compliance'],
    testing_required: ['Cap Temperature Rise Measurement', 'Mechanical Torsion and Pull Force on Base', 'High Voltage Surge Immunity (2.5 kV)'],
    searchable_text: 'IS 16102 led bulb lamp lighting energy efficiency crs scheme 2 safety self ballasted',
    is_demo: false,
  },
  {
    standard_number: 'IS 10500: 2012',
    title: 'Drinking Water - Specification',
    category: 'Food & Agriculture',
    sector: 'Public Health & Municipal Water Supplies',
    description: 'Establishes essential physical, chemical, toxic substance, and bacteriological standards for potable drinking water supplied to citizens.',
    scope: 'National reference standard for municipal piped water, packaged water, reverse osmosis plants, and institutional drinking supplies.',
    edition: '2.0',
    publication_date: '2012-05-30',
    status: 'Mandatory Reference Standard',
    scheme: 'National Public Health Standard / ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'Department of Drinking Water and Sanitation / BIS',
    source_type: 'National Potable Water Standard',
    key_requirements: ['pH acceptable limit 6.5 to 8.5', 'Total Dissolved Solids (TDS) acceptable limit 500 mg/L (permissible up to 2000 mg/L in absence of alternate source)', 'Total Hardness <= 200 mg/L; Nitrate <= 45 mg/L; Fluoride <= 1.0 mg/L'],
    testing_required: ['Complete Chemical Anion & Cation Titration', 'Trace Metal Atomic Absorption Spectrometry', 'Total Coliform MPN Fermentation Test'],
    searchable_text: 'IS 10500 drinking water potable water municipal tds ph fluoride heavy metals water quality',
    is_demo: false,
  },
  {
    standard_number: 'IS 15700: 2018',
    title: 'Quality Management Systems - Requirements for Service Quality by Public Service Organizations (Sevottam)',
    category: 'Services & Management',
    sector: 'Public Administration & Service Delivery',
    description: 'Provides framework for citizen charters, service standard benchmarks, public grievance redressal mechanisms, and capability development.',
    scope: 'Applicable to central ministries, state government departments, autonomous bodies, and municipal service corporations.',
    edition: '2.0',
    publication_date: '2018-09-10',
    status: 'Voluntary Management Certification',
    scheme: 'BIS Management Systems Certification (Scheme VII)',
    document_url: 'https://www.bis.gov.in/',
    source: 'Bureau of Indian Standards',
    source_type: 'Service Quality Standard',
    key_requirements: ['Published Citizen Charter with defined time commitments', 'Multi-channel grievance redressal with time-bound escalation', 'Periodic citizen satisfaction index surveys'],
    testing_required: ['Third-Party Management System Audit', 'Grievance Resolution Process Audit', 'Stakeholder Feedback Verification'],
    searchable_text: 'IS 15700 sevottam public service delivery citizen charter grievance redressal quality management',
    is_demo: false,
  },
  {
    standard_number: 'IS 13450 (Part 1): 2018 / IEC 60601-1: 2012',
    title: 'Medical Electrical Equipment - Part 1: General Requirements for Basic Safety and Essential Performance',
    category: 'Medical Devices',
    sector: 'Healthcare & Medical Devices',
    description: 'Establishes fundamental patient and operator electrical safety, thermal safety, electromagnetic compatibility, and risk management for active medical devices.',
    scope: 'Mandatory under CDSCO Medical Device Rules for hospital monitors, surgical generators, infusion pumps, and diagnostic equipment.',
    edition: '3.0',
    publication_date: '2018-10-15',
    status: 'Mandatory (Medical Device Rules)',
    scheme: 'BIS Medical Devices Standard / CDSCO Recognition',
    document_url: 'https://www.bis.gov.in/',
    source: 'CDSCO / Ministry of Health / BIS',
    source_type: 'Medical Device Regulations',
    key_requirements: ['Earth leakage current < 500 uA under normal condition', 'Patient auxiliary leakage current < 10 uA for Type CF cardiac floating parts', 'Defibrillation proof protection on patient connections'],
    testing_required: ['Patient Isolation Barrier Breakdown Test (4 kV AC)', 'Electromagnetic Compatibility (EMC/EMI) Chamber Scan', 'Single Fault Condition Simulation Test'],
    searchable_text: 'IS 13450 medical electrical equipment patient safety cdsco hospital diagnostic device iec 60601',
    is_demo: false,
  },
  {
    standard_number: 'IS 17263: 2019',
    title: 'Textiles - Polyester Spun Yarn for Weaving and Knitting - Specification',
    category: 'Textiles & Apparel',
    sector: 'Textile Manufacturing & Apparel',
    description: 'Specifies single yarn breaking strength, count variation, twist factor, unevenness percentage (U%), and hairiness index for commercial polyester spun yarns.',
    scope: 'Applicable to textile spinning mills, synthetic fabric weavers, and industrial knitters across India.',
    edition: '1.0',
    publication_date: '2019-11-28',
    status: 'Mandatory (QCO)',
    scheme: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    document_url: 'https://www.bis.gov.in/',
    source: 'Ministry of Textiles / BIS',
    source_type: 'Man-Made Fibre & Yarn QCO',
    key_requirements: ['Breaking tenacity >= 14.5 cN/tex for knitting grade yarn', 'Coefficient of variation of count (CV%) <= 2.2%', 'Unevenness (Uster U%) strictly within IS tolerances'],
    testing_required: ['Uster Evenness Tester Measurement', 'Single Yarn Tensile Strength Tester (CRE Method)', 'Twist per Metre Electronic Counter'],
    searchable_text: 'IS 17263 polyester yarn spun yarn textile weaving knitting synthetic fabric qco isi mark',
    is_demo: false,
  },
  {
    standard_number: 'IS 9999 (DEMO): 2024',
    title: '[DEMO] Smart Internet of Things (IoT) Connected Home Devices - Interoperability & Security',
    category: 'Electrical & Electronics',
    sector: 'Smart Home & Emerging Tech',
    description: 'Sample demo standard for testing next-generation IoT sensor protocols, zero-trust cryptographic device handshake, and local edge fallback resilience.',
    scope: 'Demonstration standard record for platform verification workflows.',
    edition: '1.0-DEMO',
    publication_date: '2024-01-01',
    status: 'DEMO / Prototype Standard',
    scheme: 'Demo Evaluation Scheme',
    document_url: 'https://www.manakonline.in',
    source: 'BIS Saarthi AI Synthetic Demo Registry',
    source_type: 'DEMO SAMPLE RECORD',
    key_requirements: ['AES-256 encrypted local credential storage (DEMO)', 'TLS 1.3 mutual handshake with gateway (DEMO)'],
    testing_required: ['Penetration Testing Simulation (DEMO)', 'Firmware Tamper Resistance Check (DEMO)'],
    searchable_text: 'IS 9999 demo iot smart home sensor security sample prototype test',
    is_demo: true,
  },
];

const documentsData = [
  {
    document_name: 'BIS Product Certification Scheme I Manual',
    document_type: 'Official Certification Manual',
    source: 'BIS ManakOnline',
    source_url: 'https://www.manakonline.in',
    category: 'Product Certification',
    publication_date: '2022-01-01',
    extracted_text: 'Under Scheme I (ISI Mark), domestic manufacturers apply on ManakOnline portal. BIS officers perform factory inspection, sample testing at recognized labs, and grant CM/L licence for verified compliance with relevant Indian Standards.',
    processing_status: 'PROCESSED',
    is_demo: false,
  },
  {
    document_name: 'Compulsory Registration Scheme (CRS) Operational Guidelines',
    document_type: 'Regulatory Scheme Guidelines',
    source: 'BIS CRS Portal',
    source_url: 'https://www.crsbis.in/BIS/',
    category: 'Information Technology & Electronics',
    publication_date: '2021-06-01',
    extracted_text: 'The Compulsory Registration Scheme (CRS) mandates that notified electronic and IT items (laptops, power adapters, lithium batteries, LED lighting) must be tested by BIS recognized testing laboratories and registered before market release.',
    processing_status: 'PROCESSED',
    is_demo: false,
  },
  {
    document_name: 'BIS Hallmarking Scheme IV & HUID System Standard Operating Procedure',
    document_type: 'Hallmarking SOP & Citizen Guide',
    source: 'BIS Hallmarking Division',
    source_url: 'https://www.bis.gov.in/hallmarking-2/',
    category: 'Precious Metals & Hallmarking',
    publication_date: '2021-07-01',
    extracted_text: 'Hallmarking of gold jewellery guarantees purity. Each article receives 3 marks: BIS Triangular Logo, Fineness purity grade (e.g., 916 for 22K), and 6-digit alphanumeric HUID (Hallmark Unique Identification). Consumers can verify HUID on BIS Care App.',
    processing_status: 'PROCESSED',
    is_demo: false,
  },
  {
    document_name: 'BIS Laboratory Recognition Scheme (LRS) Manual',
    document_type: 'Laboratory Accreditation Guidelines',
    source: 'BIS LIMS Portal',
    source_url: 'https://www.limsbis.in',
    category: 'Laboratory Services',
    publication_date: '2021-03-15',
    extracted_text: 'The BIS Laboratory Recognition Scheme (LRS) governs third-party testing laboratories. Recognized labs process sample test requests (TRs) issued through ManakOnline and generate legally binding test reports linked into LIMS.',
    processing_status: 'PROCESSED',
    is_demo: false,
  },
];

const documentChunksData = [
  {
    standard_number: 'IS 302 (Part 2/Sec 3): 2007',
    chunk_text: 'Electric kettles must comply with IS 302 (Part 2/Sec 3): 2007. Key safety tests include high-voltage insulation withstand at 1500V AC, automatic dry-boil thermal cutoff operation, double insulated internal wiring, and earthing continuity for user safety.',
    page_number: 4,
    section: 'Clause 8 - Thermal Safety and Insulation',
    is_demo: false,
  },
  {
    standard_number: 'IS 1417: 2016',
    chunk_text: 'Gold jewellery hallmarking in India is governed by IS 1417: 2016. Every hallmarked piece features 3 mandatory marks: BIS Logo, purity in karats and fineness (e.g. 22K916), and a 6-digit alphanumeric Hallmark Unique Identification (HUID) code engraved by a BIS-recognized Assaying and Hallmarking Centre (AHC).',
    page_number: 2,
    section: 'Clause 6 - Marking and HUID Traceability',
    is_demo: false,
  },
  {
    standard_number: 'IS 13252 (Part 1): 2010',
    chunk_text: 'Information technology equipment including laptops, monitors, mobile chargers, and power supplies must undergo CRS registration under IS 13252 (Part 1): 2010. Tests verify creepage distance, flame-retardant enclosures (V-0/V-1), and thermal dissipation.',
    page_number: 5,
    section: 'Clause 4 - Protection against Electrical Hazards',
    is_demo: false,
  },
  {
    standard_number: 'IS 15410: 2003',
    chunk_text: 'Packaged natural mineral water bottling must comply with IS 15410: 2003 under mandatory ISI mark certification. Water must show zero detectable coliforms per 250ml, Total Dissolved Solids between 150-700 mg/L, and use food-grade virgin PET or glass bottles.',
    page_number: 3,
    section: 'Clause 5 - Microbiological & Mineral Limits',
    is_demo: false,
  },
];

const productsData = [
  {
    product_name: 'Pigeon Stainless Steel Electric Kettle 1.8L',
    category: 'Household Electrical Appliances',
    brand: 'Pigeon',
    manufacturer: 'Stovekraft Private Limited, Bengaluru',
    model_number: 'EK-1800W',
    standard_number: 'IS 302 (Part 2/Sec 3): 2007',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-8400012395',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Havells Aqua Plus 1.2L Double Wall Kettle',
    category: 'Household Electrical Appliances',
    brand: 'Havells',
    manufacturer: 'Havells India Limited, Haridwar',
    model_number: 'GHB-KTL120',
    standard_number: 'IS 302 (Part 2/Sec 3): 2007',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-7200045612',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Prestige PKOSS 1.5L Electric Kettle',
    category: 'Household Electrical Appliances',
    brand: 'Prestige',
    manufacturer: 'TTK Prestige Limited, Hosur',
    model_number: 'PKOSS-15',
    standard_number: 'IS 302 (Part 2/Sec 3): 2007',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-9100038291',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Apple 67W USB-C Power Adapter',
    category: 'Information Technology & Power Supply',
    brand: 'Apple',
    manufacturer: 'Salcomp Manufacturing India Pvt Ltd, Sriperumbudur',
    model_number: 'A2518',
    standard_number: 'IS 13252 (Part 1): 2010',
    certification_status: 'CERTIFIED',
    registration_number: 'R-41009823',
    source: 'BIS CRS Portal',
    source_url: 'https://www.crsbis.in/BIS/',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Samsung 25W Super Fast Wall Charger',
    category: 'Information Technology & Power Supply',
    brand: 'Samsung',
    manufacturer: 'Samsung India Electronics Pvt Ltd, Noida',
    model_number: 'EP-TA800',
    standard_number: 'IS 13252 (Part 1): 2010',
    certification_status: 'CERTIFIED',
    registration_number: 'R-41012399',
    source: 'BIS CRS Portal',
    source_url: 'https://www.crsbis.in/BIS/',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Mi 33W SonicCharge 2.0 Fast Charger',
    category: 'Information Technology & Power Supply',
    brand: 'Xiaomi',
    manufacturer: 'DBG Technology India Pvt Ltd, Bawal Haryana',
    model_number: 'MDY-11-EX',
    standard_number: 'IS 13252 (Part 1): 2010',
    certification_status: 'CERTIFIED',
    registration_number: 'R-41028711',
    source: 'BIS CRS Portal',
    source_url: 'https://www.crsbis.in/BIS/',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Tata Tiscon 550D Super Ductile TMT Rebar 12mm',
    category: 'Construction & Civil',
    brand: 'Tata Tiscon',
    manufacturer: 'Tata Steel Limited, Jamshedpur',
    model_number: 'SD-550D-12',
    standard_number: 'IS 1786: 2008',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-0012890',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'JSW Neosteel 500D Fe TMT Rebar 16mm',
    category: 'Construction & Civil',
    brand: 'JSW Neosteel',
    manufacturer: 'JSW Steel Limited, Toranagallu Bellary',
    model_number: 'NS-500D-16',
    standard_number: 'IS 1786: 2008',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-0029811',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Himalayan Natural Mineral Water 1L Bottle',
    category: 'Packaged Beverages',
    brand: 'Himalayan',
    manufacturer: 'Tata Consumer Products Limited, Paonta Sahib HP',
    model_number: 'HNMW-1000',
    standard_number: 'IS 15410: 2003',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-5100088921',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Catch Natural Spring Water 750ml',
    category: 'Packaged Beverages',
    brand: 'Catch',
    manufacturer: 'DS Group, Kullu Himachal Pradesh',
    model_number: 'CNSW-750',
    standard_number: 'IS 15410: 2003',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-5200019481',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Polycab 2.5 sq mm Green FR PVC Wire 90m',
    category: 'Electrical Cables & Wires',
    brand: 'Polycab',
    manufacturer: 'Polycab India Limited, Halol Gujarat',
    model_number: 'FR-2.5-GRN',
    standard_number: 'IS 694: 2010',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-30004921',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Havells LifeLine Plus 1.5 sq mm Red Wire',
    category: 'Electrical Cables & Wires',
    brand: 'Havells',
    manufacturer: 'Havells India Limited, Alwar Rajasthan',
    model_number: 'LLP-1.5-RED',
    standard_number: 'IS 694: 2010',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-30129841',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Anchor by Panasonic Roma 6A 3-Pin Socket with Safety Shutter',
    category: 'Electrical Accessories',
    brand: 'Anchor Roma',
    manufacturer: 'Panasonic Life Solutions India Pvt Ltd, Daman',
    model_number: 'ROMA-6A-SKT',
    standard_number: 'IS 1293: 2019',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-8200192384',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Schneider Electric AvatarOn 16A 3-Pin Combined Switch & Socket',
    category: 'Electrical Accessories',
    brand: 'Schneider Electric',
    manufacturer: 'Schneider Electric India Pvt Ltd, Chennai',
    model_number: 'AVT-16A-SS',
    standard_number: 'IS 1293: 2019',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-8300291044',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Vega Crux Full Face ISI Certified Helmet (L)',
    category: 'Safety & Automotive Headgear',
    brand: 'Vega',
    manufacturer: 'Vega Auto Accessories Pvt Ltd, Belagavi Karnataka',
    model_number: 'CRUX-L-BLK',
    standard_number: 'IS 4151: 2020',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-6100029311',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Studds Ninja Elite Flip-Up Helmet',
    category: 'Safety & Automotive Headgear',
    brand: 'Studds',
    manufacturer: 'Studds Accessories Limited, Faridabad Haryana',
    model_number: 'NINJA-ELITE-M',
    standard_number: 'IS 4151: 2020',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-6100048192',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Funskool Giggles Activity Stacker Toy for Toddlers',
    category: 'Children Toys & Games',
    brand: 'Funskool',
    manufacturer: 'Funskool India Limited, Ranipet Tamil Nadu',
    model_number: 'FNS-STK-01',
    standard_number: 'IS 9873 (Part 1): 2019',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-7300019283',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Philips 9W B22 Cool Daylight LED Bulb (Pack of 2)',
    category: 'Lighting & Electronics',
    brand: 'Philips',
    manufacturer: 'Signify Innovations India Ltd, Mohali Punjab',
    model_number: 'PHL-LED-9W',
    standard_number: 'IS 16102 (Part 1): 2012',
    certification_status: 'CERTIFIED',
    registration_number: 'R-41001294',
    source: 'BIS CRS Portal',
    source_url: 'https://www.crsbis.in/BIS/',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'UltraTech Super 53 Grade Ordinary Portland Cement 50kg',
    category: 'Construction & Civil',
    brand: 'UltraTech Cement',
    manufacturer: 'UltraTech Cement Limited, Rajpura Punjab',
    model_number: 'UTC-OPC-53',
    standard_number: 'IS 269: 2015',
    certification_status: 'CERTIFIED',
    registration_number: 'CM/L-1100029381',
    source: 'BIS ManakOnline Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  {
    product_name: 'Waaree 540W Mono PERC Solar PV Module',
    category: 'Solar & Renewable Energy',
    brand: 'Waaree',
    manufacturer: 'Waaree Energies Limited, Surat Gujarat',
    model_number: 'W-540-PERC',
    standard_number: 'IS 14286 / IEC 61215: 2010',
    certification_status: 'CERTIFIED',
    registration_number: 'R-41098231',
    source: 'BIS CRS Portal',
    source_url: 'https://www.crsbis.in/BIS/',
    verification_status: 'VERIFIED',
    is_demo: false,
  },
  // DEMO PRODUCT RECORDS (CLEANLY MARKED WITH is_demo: true)
  {
    product_name: '[DEMO] Smart Home Hub Pro 2.0 (Sample Test Unit)',
    category: 'Smart Home & Emerging Tech',
    brand: 'DEMO-TECH',
    manufacturer: 'Demo Prototyping Labs India Ltd',
    model_number: 'DEMO-HUB-2024',
    standard_number: 'IS 9999 (DEMO): 2024',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CML-000001',
    source: 'BIS Saarthi AI Synthetic Demo Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] EcoClean BioDegradable Water Filter Bottle',
    category: 'Packaged Beverages & Filtration',
    brand: 'DEMO-PURE',
    manufacturer: 'Demo Filtration Systems Pvt Ltd',
    model_number: 'DEMO-ECO-500',
    standard_number: 'IS 15410: 2003',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CML-000002',
    source: 'BIS Saarthi AI Synthetic Demo Registry',
    source_url: 'https://www.manakonline.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] Uncertified Road Side Ceramic Heater (Fake ISI Stamp Test)',
    category: 'Household Electrical Appliances',
    brand: 'Generic Unbranded',
    manufacturer: 'Unknown / Unlicensed Assembler',
    model_number: 'UNLICENSED-99',
    standard_number: 'IS 302 (Part 2/Sec 3): 2007',
    certification_status: 'NOT CERTIFIED',
    registration_number: 'INVALID-99999999',
    source: 'Synthetic Enforcement Test Case',
    source_url: 'https://www.manakonline.in',
    verification_status: 'NOT VERIFIED',
    is_demo: true,
  },
  {
    product_name: '[DEMO] UltraSound Therapeutic Probe Model X (Testing Record)',
    category: 'Medical Devices',
    brand: 'DEMO-MED',
    manufacturer: 'Demo Healthcare Technologies Ltd',
    model_number: 'DEMO-MED-US1',
    standard_number: 'IS 13450 (Part 1): 2018 / IEC 60601-1: 2012',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-REG-98124',
    source: 'Synthetic Medical Test Case',
    source_url: 'https://www.bis.gov.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] High Tenacity Recycled Poly Yarn Spool 5kg',
    category: 'Textiles & Apparel',
    brand: 'DEMO-SPIN',
    manufacturer: 'Demo Synthetic Spinners India',
    model_number: 'DEMO-YRN-50',
    standard_number: 'IS 17263: 2019',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CML-441199',
    source: 'Synthetic Textile Test Registry',
    source_url: 'https://www.bis.gov.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] Substation Grade Insulating Mat 1000x2000mm Class A',
    category: 'Industrial Safety & Switchgear',
    brand: 'DEMO-GUARD',
    manufacturer: 'Demo Rubber & Safety Polymers Ltd',
    model_number: 'DEMO-MAT-33KV',
    standard_number: 'IS 15652: 2006',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CML-552211',
    source: 'Synthetic Industrial Test Registry',
    source_url: 'https://www.bis.gov.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] Quick Charge GaN 100W Laptop Power Brick',
    category: 'Information Technology & Power Supply',
    brand: 'DEMO-GAN',
    manufacturer: 'Demo Power Solutions Gurgaon',
    model_number: 'DEMO-GAN-100W',
    standard_number: 'IS 13252 (Part 1): 2010',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CRS-771122',
    source: 'Synthetic CRS Registry',
    source_url: 'https://www.crsbis.in/BIS/',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] Lightweight Urban Commuter Bike Helmet (Size M)',
    category: 'Safety & Automotive Headgear',
    brand: 'DEMO-RIDE',
    manufacturer: 'Demo Headgear Innovations Ltd',
    model_number: 'DEMO-HLM-200',
    standard_number: 'IS 4151: 2020',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CML-998811',
    source: 'Synthetic Helmet Registry',
    source_url: 'https://www.bis.gov.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] Wooden Educational Shape Sorter for Toddlers',
    category: 'Children Toys & Games',
    brand: 'DEMO-TOYS',
    manufacturer: 'Demo Artisan Toymakers Mysore',
    model_number: 'DEMO-TOY-SHP',
    standard_number: 'IS 9873 (Part 1): 2019',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CML-332211',
    source: 'Synthetic Toy Safety Registry',
    source_url: 'https://www.bis.gov.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
  {
    product_name: '[DEMO] 32A Industrial Weatherproof Plug & Coupler Set',
    category: 'Electrical Accessories',
    brand: 'DEMO-SOCKET',
    manufacturer: 'Demo Industrial Electrics Pune',
    model_number: 'DEMO-PLG-32A',
    standard_number: 'IS 1293: 2019',
    certification_status: 'DEMO / SAMPLE RECORD',
    registration_number: 'DEMO-CML-128833',
    source: 'Synthetic Electrical Accessories Registry',
    source_url: 'https://www.bis.gov.in',
    verification_status: 'MATCH FOUND',
    is_demo: true,
  },
];

const hallmarkingData = [
  {
    product_type: '22K Gold Traditional Kada / Bangle',
    huid: 'K92A8M',
    purity_grade: '22K (916)',
    purity_description: '91.6% Pure Gold Fineness under IS 1417',
    jeweller_name: 'Tanishq (Titan Company Ltd), Indiranagar Bengaluru',
    jeweller_registration_no: 'HM/R-KA-560038-001',
    ahc_center: 'South India Assaying & Hallmarking Centre, Bengaluru',
    hallmark_information: '3 Mandatory Marks verified: BIS Triangular Standard Logo, 22K916 Fineness Mark, 6-digit alphanumeric HUID code K92A8M.',
    verification_information: 'Assayed via Fire Assay (Cupellation method IS 1418). Clean match on official BIS Care & ManakOnline registry.',
    is_demo: false,
  },
  {
    product_type: '18K Diamond Studded Gold Ring',
    huid: 'A78X4Y',
    purity_grade: '18K (750)',
    purity_description: '75.0% Pure Gold Fineness under IS 1417',
    jeweller_name: 'Kalyan Jewellers India Ltd, T. Nagar Chennai',
    jeweller_registration_no: 'HM/R-TN-600017-042',
    ahc_center: 'Madras Precious Metals Assaying Centre, Chennai',
    hallmark_information: '3 Mandatory Marks verified: BIS Logo, 18K750 Fineness, HUID A78X4Y.',
    verification_information: 'Assayed and laser etched. Valid hallmarking registration.',
    is_demo: false,
  },
  {
    product_type: '24K Gold Minted Bullion Coin 10g',
    huid: 'B39W1Q',
    purity_grade: '24K (999)',
    purity_description: '99.9% Fine Gold bullion under IS 1417',
    jeweller_name: 'MMTC-PAMP India Private Ltd, New Delhi',
    jeweller_registration_no: 'HM/R-DL-110001-008',
    ahc_center: 'MMTC-PAMP Integrated Refining & Assaying Facility, Mewat Haryana',
    hallmark_information: 'BIS Standard Hallmark with 24K999 Fineness stamp and HUID B39W1Q.',
    verification_information: 'Refined under LBMA & BIS standards. Fully verified.',
    is_demo: false,
  },
  {
    product_type: '14K Rose Gold Floral Pendant',
    huid: 'C52M9L',
    purity_grade: '14K (585)',
    purity_description: '58.5% Fine Gold alloy under IS 1417',
    jeweller_name: 'CaratLane Trading Pvt Ltd, Mumbai',
    jeweller_registration_no: 'HM/R-MH-400050-019',
    ahc_center: 'Zaveri Bazaar Assaying Centre, Mumbai',
    hallmark_information: '3 Mandatory Marks verified: BIS Logo, 14K585, HUID C52M9L.',
    verification_information: 'Compliant with mandatory hallmarking notifications.',
    is_demo: false,
  },
  {
    product_type: '[DEMO] 22K Gold Antique Necklace (Sample Record)',
    huid: 'DEMO99',
    purity_grade: '22K (916)',
    purity_description: '[DEMO] 91.6% Pure Gold Fineness under IS 1417',
    jeweller_name: 'Demo Certified Jewellers India Pvt Ltd',
    jeweller_registration_no: 'DEMO-HM-001',
    ahc_center: 'Demo Regional Assaying Centre',
    hallmark_information: '[DEMO RECORD] Triangular logo, 916 mark, and DEMO99 test HUID.',
    verification_information: '[DEMO RECORD] Test entry for simulated verification.',
    is_demo: true,
  },
];

const laboratoriesData = [
  {
    name: 'Central Laboratory Sahibabad (BIS Operational Branch Lab)',
    state: 'Uttar Pradesh',
    city: 'Sahibabad / Ghaziabad',
    address: 'Plot No. 20/9, Site IV, Industrial Area, Sahibabad, UP - 201010',
    contact_info: '+91 120 2895100',
    email: 'clsb-bis@gov.in',
    recognition_status: 'BIS Branch Lab',
    product_category: 'Electrical Appliances, Cables, Steel & IT Devices',
    services: 'Full IS testing for Scheme I ISI mark and CRS Scheme II verification',
    testing_categories: ['Electrical Safety', 'Mechanical Strength', 'Chemical Spectroscopy', 'High Voltage Breakdown'],
    supported_standards: ['IS 302 (Part 2/Sec 3): 2007', 'IS 13252 (Part 1): 2010', 'IS 694: 2010', 'IS 1786: 2008', 'IS 1293: 2019'],
    is_demo: false,
  },
  {
    name: 'National Test House (NTH Northern Region)',
    state: 'Delhi NCR',
    city: 'New Delhi / Ghaziabad',
    address: 'Kamla Nehru Nagar, Raj Nagar, Ghaziabad, Delhi NCR - 201002',
    contact_info: '+91 120 2783456',
    email: 'nthnr-bis@gov.in',
    recognition_status: 'BIS Recognized',
    product_category: 'Electrical, Solar Photovoltaic, Mineral Water & Civil Materials',
    services: 'NABL accredited and BIS recognized testing under LIMS',
    testing_categories: ['Solar PV Modules', 'Microbiological Water Purity', 'Civil Mortar Compression', 'Toy Safety'],
    supported_standards: ['IS 302 (Part 2/Sec 3): 2007', 'IS 14286 / IEC 61215: 2010', 'IS 15410: 2003', 'IS 9873 (Part 1): 2019', 'IS 269: 2015'],
    is_demo: false,
  },
  {
    name: 'Electrical Research and Development Association (ERDA)',
    state: 'Gujarat',
    city: 'Vadodara',
    address: 'ERDA Road, Makarpura Industrial Estate, Vadodara, Gujarat - 390010',
    contact_info: '+91 265 2642942',
    email: 'erda-lab@erda.org',
    recognition_status: 'BIS Recognized',
    product_category: 'Transformers, Switchgear, Household Appliances & Solar Modules',
    services: 'High voltage electrical testing, surge testing, and environmental endurance',
    testing_categories: ['High Voltage Surge', 'Dielectric Strength', 'Flammability & Glow Wire', 'Thermal Cycling'],
    supported_standards: ['IS 302 (Part 2/Sec 3): 2007', 'IS 14286 / IEC 61215: 2010', 'IS 16102 (Part 1): 2012', 'IS 15652: 2006'],
    is_demo: false,
  },
  {
    name: 'CPRI (Central Power Research Institute)',
    state: 'Karnataka',
    city: 'Bengaluru',
    address: 'Prof. Sir C.V. Raman Road, Sadashivanagar, Bengaluru - 560080',
    contact_info: '+91 80 22072211',
    email: 'cpri-testing@cpri.in',
    recognition_status: 'BIS Recognized',
    product_category: 'High Voltage Cables, Insulation, Motors, EV Chargers & Switchgear',
    services: 'Apex electrical power research and testing authority of India',
    testing_categories: ['Cable Insulation Breakdown', 'Short-Circuit Capacity', 'Seismic Vibration', 'Dielectric Losses'],
    supported_standards: ['IS 302 (Part 2/Sec 3): 2007', 'IS 694: 2010', 'IS 15652: 2006', 'IS 1293: 2019'],
    is_demo: false,
  },
  {
    name: 'IIT Madras Sophisticated Analytical Instrument Facility (SAIF)',
    state: 'Tamil Nadu',
    city: 'Chennai',
    address: 'IIT Madras Campus, Sardar Patel Road, Guindy, Chennai - 600036',
    contact_info: '+91 44 22574935',
    email: 'saif-iitm@iitm.ac.in',
    recognition_status: 'BIS Recognized',
    product_category: 'Precious Metals Assay, Chemical Analysis & Advanced Materials',
    services: 'Fire assay cupellation, ICP-MS heavy metal detection, FTIR spectroscopy',
    testing_categories: ['Gold Fineness Assay', 'Heavy Metal ICP-MS', 'Polymer FTIR Spectroscopy'],
    supported_standards: ['IS 1417: 2016', 'IS 15410: 2003', 'IS 14534: 1998', 'IS 10500: 2012'],
    is_demo: false,
  },
  {
    name: 'National Test House (NTH Southern Region)',
    state: 'Tamil Nadu',
    city: 'Chennai',
    address: 'Tharamani, CSIR Road, Chennai, Tamil Nadu - 600113',
    contact_info: '+91 44 22541444',
    email: 'nthcr-bis@gov.in',
    recognition_status: 'BIS Recognized',
    product_category: 'Textiles, Civil Engineering, Rubber, Chemicals & Metals',
    services: 'Universal tensile testing, yarn count analysis, rubber breakdown',
    testing_categories: ['Textile Tensile & Count', 'Steel Rebar UTM Tensile', 'Rubber Breakdown'],
    supported_standards: ['IS 1786: 2008', 'IS 17263: 2019', 'IS 269: 2015', 'IS 15652: 2006'],
    is_demo: false,
  },
  {
    name: 'CIPET: Centre for Skilling and Technical Support (CSTS)',
    state: 'Gujarat',
    city: 'Ahmedabad',
    address: 'Plot No. 630, Phase-IV, GIDC Vatva, Ahmedabad - 382445',
    contact_info: '+91 79 25832053',
    email: 'cipet-ahmedabad@gov.in',
    recognition_status: 'BIS Recognized',
    product_category: 'Plastics, Polymer Pipes, Water Storage Tanks & Toy Safety',
    services: 'Mechanical plastic testing, polymer identification, migration testing',
    testing_categories: ['Polymer Migration', 'Toy Mechanical Strength', 'Tensile Stress on Plastics'],
    supported_standards: ['IS 9873 (Part 1): 2019', 'IS 14534: 1998', 'IS 15410: 2003'],
    is_demo: false,
  },
  {
    name: 'Regional Testing Centre (WR) Mumbai',
    state: 'Maharashtra',
    city: 'Mumbai',
    address: 'Kurla Andheri Road, Sakinaka, Mumbai, Maharashtra - 400072',
    contact_info: '+91 22 28512345',
    email: 'rtcwr-mumbai@gov.in',
    recognition_status: 'BIS Recognized',
    product_category: 'Electrical Accessories, Domestic Appliances, Fasteners & Toys',
    services: 'Plug & socket endurance, drop testing, thermal glow wire',
    testing_categories: ['Socket Insertion Endurance', 'Thermal Glow Wire 850C', 'Drop & Impact Attenuation'],
    supported_standards: ['IS 1293: 2019', 'IS 4151: 2020', 'IS 9873 (Part 1): 2019', 'IS 302 (Part 2/Sec 3): 2007'],
    is_demo: false,
  },
  {
    name: 'Central Institute of Mining and Fuel Research (CSIR-CIMFR)',
    state: 'Jharkhand',
    city: 'Dhanbad',
    address: 'Barwa Road, Dhanbad, Jharkhand - 826015',
    contact_info: '+91 326 2296003',
    email: 'cimfr-testing@csir.res.in',
    recognition_status: 'BIS Recognized',
    product_category: 'Flameproof Electrical Equipment, High-Tension Cables & Mining Gear',
    services: 'Explosion-proof enclosure testing, flameproof testing under IS/IEC 60079',
    testing_categories: ['Explosion Pressure Chamber', 'Flame Arrestor Inspection', 'Mining Safety Certification'],
    supported_standards: ['IS 694: 2010', 'IS 15652: 2006'],
    is_demo: false,
  },
  {
    name: 'Western Regional Laboratory (BIS WRL)',
    state: 'Maharashtra',
    city: 'Mumbai / Thane',
    address: 'Plot No. E-9, Road No. 8, MIDC, Andheri East, Mumbai - 400093',
    contact_info: '+91 22 28329295',
    email: 'wrl-bis@gov.in',
    recognition_status: 'BIS Branch Lab',
    product_category: 'Packaged Food, Water, Chemical Analysis, Consumer Electronics',
    services: 'Official regional branch testing facility of BIS',
    testing_categories: ['Microbiological Incubation', 'Food Contaminants Spectrometry', 'Electronics Safety Verification'],
    supported_standards: ['IS 15410: 2003', 'IS 10500: 2012', 'IS 13252 (Part 1): 2010', 'IS 16046 (Part 2): 2018 / IEC 62133-2: 2017'],
    is_demo: false,
  },
];

const bisServicesData = [
  {
    service_name: 'BIS Product Certification Scheme (Scheme I) — ISI Mark',
    category: 'Product Certification',
    description: 'Core product certification scheme granting CM/L (Certification Marks Licence) for domestic manufacturers complying with mandatory or voluntary Indian Standards.',
    eligibility: 'Domestic manufacturers having required in-house manufacturing machinery and testing facilities for the applicable Indian Standard.',
    process: [
      { step: 1, title: 'Identify Applicable Indian Standard', desc: 'Determine the exact IS number on BIS ManakOnline.' },
      { step: 2, title: 'Check Quality Control Order (QCO)', desc: 'Verify whether the product falls under mandatory certification.' },
      { step: 3, title: 'Submit Online Application on ManakOnline', desc: 'Upload factory premises details, machinery list, and test equipment checklist.' },
      { step: 4, title: 'Factory Inspection & Sample Drawing', desc: 'BIS inspecting officer visits the factory and draws representative production samples.' },
      { step: 5, title: 'Laboratory Testing', desc: 'Samples tested at a BIS Recognized Lab under the BIS LIMS portal.' },
      { step: 6, title: 'Grant of CM/L Licence', desc: 'Upon successful test report, 7-digit CM/L licence number is assigned for ISI Mark application.' }
    ],
    required_documents: ['Factory registration certificate / MSME Udyam Registration', 'List of manufacturing machinery and test equipment', 'Plant layout diagram and calibration certificates', 'Authorised signatory authorization letter'],
    msme_concession: '50% concession on application fee and marking fee for Micro enterprises; 20% for Small enterprises.',
    portal_url: 'https://www.manakonline.in',
    is_demo: false,
  },
  {
    service_name: 'Compulsory Registration Scheme (Scheme II) — CRS',
    category: 'Information Technology & Electronics',
    description: 'Mandatory self-declaration registration scheme for notified electronic, IT, solar, and lighting items under MeitY and MNRE orders.',
    eligibility: 'Manufacturers of notified electronic/IT goods (domestic and foreign).',
    process: [
      { step: 1, title: 'Submit Product to BIS Recognized Lab', desc: 'Dispatch product batch to a BIS recognized testing lab for IS 13252 / IS 16046 / IS 14286 testing.' },
      { step: 2, title: 'Obtain Test Report with QR Code', desc: 'Receive validated test report via BIS LIMS.' },
      { step: 3, title: 'Apply on CRS Online Portal', desc: 'Submit registration application with test report and manufacturer undertaking.' },
      { step: 4, title: 'Grant of CRS Registration (R-XXXXXXXX)', desc: 'BIS issues unique Registration Number for product batch and model range.' }
    ],
    required_documents: ['BIS Lab Test Report', 'Manufacturer Business Licence & Brand Owner Authorization (Form VI)', 'Affidavit-cum-Undertaking (Form C)'],
    msme_concession: 'Streamlined online processing within 15 working days.',
    portal_url: 'https://www.crsbis.in/BIS/',
    is_demo: false,
  },
  {
    service_name: 'BIS Hallmarking Scheme (Scheme IV) — Gold & Silver',
    category: 'Precious Metals & Hallmarking',
    description: 'Mandatory purity certification for gold jewellery and silver artefacts featuring the 6-digit Hallmark Unique Identification (HUID) code.',
    eligibility: 'Jewellers and Assaying & Hallmarking Centres (AHCs).',
    process: [
      { step: 1, title: 'Online Registration of Jeweller', desc: 'Instant registration on ManakOnline Hallmarking module.' },
      { step: 2, title: 'Dispatch Jewellery to AHC', desc: 'Send articles to a BIS-recognized Assaying & Hallmarking Centre.' },
      { step: 3, title: 'Fire Assay & Laser Etching', desc: 'AHC performs purity testing (IS 1417/IS 1418) and lasers the 3 marks and HUID.' },
      { step: 4, title: 'Traceability on BIS Care App', desc: 'Consumer can verify the HUID code for jeweller identity, AHC name, and purity.' }
    ],
    required_documents: ['GST Registration Certificate', 'Proof of outlet address', 'Director / Proprietor PAN and Aadhaar'],
    msme_concession: 'Zero registration fee for jewellers with turnover under Rs 40 Lakhs.',
    portal_url: 'https://www.bis.gov.in/hallmarking-2/',
    is_demo: false,
  },
  {
    service_name: 'Foreign Manufacturers Certification Scheme (Scheme III) — FMCS',
    category: 'International Certification',
    description: 'Certification scheme enabling overseas manufacturing plants outside India to apply for and use the ISI Mark on goods exported to India.',
    eligibility: 'Foreign manufacturing units having physical manufacturing plant outside India.',
    process: [
      { step: 1, title: 'Submit FMCS Application (Form VI)', desc: 'Apply with Authorized Indian Representative (AIR) details.' },
      { step: 2, title: 'Factory Audit by BIS Delegation', desc: 'BIS officers inspect overseas manufacturing facility and draw samples.' },
      { step: 3, title: 'Sample Clearance in India', desc: 'Samples cleared through Indian Customs and tested in BIS laboratories.' },
      { step: 4, title: 'Grant of FMCS Licence & Performance Bank Guarantee', desc: 'Licence granted upon submission of PBG.' }
    ],
    required_documents: ['Authorized Indian Representative (AIR) Agreement', 'Overseas Plant Registration & Manufacturing Process Flowchart', 'In-house testing facility documentation'],
    portal_url: 'https://www.manakonline.in',
    is_demo: false,
  },
  {
    service_name: 'BIS Laboratory Recognition Scheme (LRS / LIMS)',
    category: 'Laboratory Services',
    description: 'Recognition and audit system for commercial and government testing laboratories to test samples for BIS certification schemes.',
    eligibility: 'NABL accredited testing laboratories operating under ISO/IEC 17025.',
    process: [
      { step: 1, title: 'Apply on BIS LIMS Portal', desc: 'Submit scope of testing standards and NABL accreditation documents.' },
      { step: 2, title: 'Technical Assessment by BIS Assessment Team', desc: 'Audit of testing apparatus, environmental controls, and technician proficiency.' },
      { step: 3, title: 'Grant of Recognition & Integration with LIMS', desc: 'Lab allocated sample test requests directly from ManakOnline.' }
    ],
    required_documents: ['ISO/IEC 17025 Accreditation Certificate & Scope', 'Equipment list with NABL calibration certificates', 'Staff CVs and competence records'],
    portal_url: 'https://www.limsbis.in',
    is_demo: false,
  },
  {
    service_name: 'Management Systems Certification Scheme (MSCS)',
    category: 'Management Systems',
    description: 'Third-party certification for ISO 9001 (QMS), ISO 14001 (EMS), ISO 22000 (FSMS), ISO 45001 (OH&SMS), and IS 15700 (Sevottam).',
    eligibility: 'Industrial enterprises, service corporations, hospitals, and government bodies.',
    process: [
      { step: 1, title: 'Application & Stage 1 Documentation Audit', desc: 'Review of Quality Manual and SOPs.' },
      { step: 2, title: 'Stage 2 On-Site Certification Audit', desc: 'Evaluation of system implementation and corrective actions.' },
      { step: 3, title: 'Award of ISO / IS Management Certificate', desc: 'Valid for 3 years subject to annual surveillance audits.' }
    ],
    required_documents: ['Quality Manual & Policy', 'Internal Audit & Management Review Reports', 'Scope of Operations definition'],
    portal_url: 'https://www.bis.gov.in/',
    is_demo: false,
  },
  {
    service_name: 'ECO Mark Certification Scheme',
    category: 'Environmental & Sustainability',
    description: 'Labeling of environment-friendly consumer products that comply with specific environmental criteria in addition to quality requirements of Indian Standards.',
    eligibility: 'Manufacturers of soaps, detergents, paints, paper, plastics, and batteries meeting eco-criteria.',
    process: [
      { step: 1, title: 'ISI Mark Compliance', desc: 'Ensure standard quality criteria under IS standard are satisfied.' },
      { step: 2, title: 'Environmental Criteria Verification', desc: 'Test for bio-degradability, low VOC emissions, and absence of banned heavy metals.' },
      { step: 3, title: 'Award of ECO Mark Logo (Earthen Pot symbol)', desc: 'Authorisation to print the distinctive ECO Mark on consumer packaging.' }
    ],
    required_documents: ['Pollution Control Board Consent to Operate (CTO)', 'Material Safety Data Sheets (MSDS)', 'Eco-testing reports'],
    portal_url: 'https://www.bis.gov.in/',
    is_demo: false,
  },
  {
    service_name: 'BIS Consumer Care & Grievance Redressal',
    category: 'Consumer Protection',
    description: 'Official mechanism for citizens and consumers to report fake ISI marks, hallmarking discrepancies, sub-standard products, or misleading quality claims.',
    eligibility: 'All Indian citizens and consumer advocacy groups.',
    process: [
      { step: 1, title: 'Verify Mark via BIS Care App or BISynapse', desc: 'Check CM/L or HUID validity.' },
      { step: 2, title: 'File Grievance on BIS Portal / BIS Care App', desc: 'Attach photos of fraudulent label and store purchase invoice.' },
      { step: 3, title: 'Enforcement Investigation & Raid', desc: 'BIS Enforcement team conducts surprise inspection and seizure under BIS Act 2016.' }
    ],
    required_documents: ['Purchase invoice / bill', 'Photograph of product packaging displaying defective/fake mark'],
    portal_url: 'https://www.bis.gov.in/consumer-overview/',
    is_demo: false,
  },
  {
    service_name: 'National Institute of Training for Standardization (NITS)',
    category: 'Training & Education',
    description: 'Premier training institute of BIS offering training on Indian Standards, laboratory testing protocols, quality control, and regulatory compliance.',
    eligibility: 'Industry professionals, MSME owners, laboratory technicians, and government officials.',
    process: [
      { step: 1, title: 'Select Course from NITS Calendar', desc: 'Browse standardization, testing, or auditing courses.' },
      { step: 2, title: 'Online Registration & Nomination', desc: 'Register via ManakOnline NITS training portal.' },
      { step: 3, title: 'Course Completion & Certification', desc: 'Receive BIS-certified competence certificate upon assessment.' }
    ],
    required_documents: ['Organization sponsorship letter / government employee ID'],
    portal_url: 'https://www.bis.gov.in/training/',
    is_demo: false,
  },
  {
    service_name: 'Standards Formulation & National Technical Committees',
    category: 'Standards Development',
    description: 'Public participation mechanism for drafting, revising, and amending Indian Standards through 15 Division Councils and sectional committees.',
    eligibility: 'Domain experts, academicians, industry associations, and consumer bodies.',
    process: [
      { step: 1, title: 'Proposal for New Work Item (NWIP)', desc: 'Submit standardized proposal for new standard formulation.' },
      { step: 2, title: 'Wide Circulation Draft Review', desc: 'Draft published for public comments for 60 days.' },
      { step: 3, title: 'Gazette Notification', desc: 'Finalized Indian Standard published in the Gazette of India.' }
    ],
    required_documents: ['Technical justification paper and international baseline comparison (ISO/IEC)'],
    portal_url: 'https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/indian_standards/isdetails/',
    is_demo: false,
  },
  {
    service_name: 'BIS Care Mobile App Services',
    category: 'Digital Citizen Services',
    description: 'Flagship mobile app empowering citizens to verify CM/L licences, CRS registrations, HUID codes, and submit instant geo-tagged complaints.',
    eligibility: 'General public (Android & iOS).',
    process: [
      { step: 1, title: 'Download BIS Care App from Play Store / App Store', desc: 'Install the official application.' },
      { step: 2, title: 'Use Verify Feature', desc: 'Verify CM/L number, CRS registration number, or 6-digit HUID.' },
      { step: 3, title: 'View Official Details', desc: 'Inspect manufacturer name, address, product scope, and validity status.' }
    ],
    required_documents: ['None — free citizen utility'],
    portal_url: 'https://www.bis.gov.in/consumer-overview/bis-care-app/',
    is_demo: false,
  },
  {
    service_name: 'Quality Control Order (QCO) Compliance Advisory',
    category: 'Regulatory Advisory',
    description: 'Advisory and compliance tracking service informing industries and importers about mandatory Quality Control Orders notified by Central Ministries.',
    eligibility: 'Domestic manufacturers, importers, and industry associations.',
    process: [
      { step: 1, title: 'Search Product HS Code / Category', desc: 'Check latest ministerial QCO notifications.' },
      { step: 2, title: 'Verify Implementation Date & Grace Period', desc: 'Identify transition deadlines for MSMEs.' },
      { step: 3, title: 'Initiate Certification Pathway', desc: 'Commence testing and audit prior to mandatory cutoff date.' }
    ],
    required_documents: ['Product technical data sheet and HS / ITC Code'],
    portal_url: 'https://www.bis.gov.in/standards/quality-control-orders-qcos/',
    is_demo: false,
  },
  {
    service_name: 'Standards Club in Schools and Colleges',
    category: 'Consumer Awareness & Education',
    description: 'Grassroots youth initiative establishing Standards Clubs in educational institutions to nurture quality consciousness, scientific temper, and consumer awareness.',
    eligibility: 'Recognized schools, polytechnics, and engineering colleges.',
    process: [
      { step: 1, title: 'Institution Memorandum of Understanding (MoU)', desc: 'School/College registers with nearest BIS Branch Office.' },
      { step: 2, title: 'Student Mentor Nomination', desc: 'Faculty mentor coordinates standards writing competitions and industrial visits.' },
      { step: 3, title: 'Financial Grant by BIS', desc: 'BIS provides financial support for standards club activities.' }
    ],
    required_documents: ['School / College Affiliation Certificate and Principal consent letter'],
    portal_url: 'https://www.bis.gov.in/standards-clubs/',
    is_demo: false,
  },
  {
    service_name: 'Manak Mitra Quality Ambassador Network',
    category: 'Community Engagement',
    description: 'Volunteer and quality ambassador network connecting consumer activists, youth, and technical experts to promote standardization at grassroots district levels.',
    eligibility: 'Youth volunteers and consumer advocates.',
    process: [
      { step: 1, title: 'Register on Manak Mitra Portal', desc: 'Sign up as a Quality Ambassador.' },
      { step: 2, title: 'Participate in Awareness Drives', desc: 'Distribute BIS educational materials and guide local merchants.' }
    ],
    required_documents: ['Aadhaar ID and educational qualification proof'],
    portal_url: 'https://www.bis.gov.in/',
    is_demo: false,
  },
  {
    service_name: 'Market Surveillance & Enforcement Seizure',
    category: 'Government Enforcement',
    description: 'Statutory surveillance operations conducted by BIS Enforcement Officers to detect counterfeit ISI marks, illegal hallmarking, and non-compliant goods.',
    eligibility: 'BIS Authorized Officers and Law Enforcement Agencies.',
    process: [
      { step: 1, title: 'Intelligence Gathering & Complaint Triage', desc: 'Analyze consumer complaints and retail market intelligence.' },
      { step: 2, title: 'Execution of Search & Seizure Raid', desc: 'Seize unauthorized standard marks under Section 18 of BIS Act 2016.' },
      { step: 3, title: 'Court Prosecution', desc: 'File criminal complaint before Judicial Magistrate.' }
    ],
    required_documents: ['Search Warrant / Section 18 Authorization Order under BIS Act 2016'],
    portal_url: 'https://www.bis.gov.in/enforcement/',
    is_demo: false,
  },
];

const faqsData = [
  {
    question: 'What is HUID in gold jewellery hallmarking and how do I verify it?',
    answer: 'HUID (Hallmark Unique Identification) is a 6-digit alphanumeric code laser-etched onto every piece of hallmarked gold jewellery. Consumers can verify the code instantly on the BIS Care App or BISynapse to confirm the jeweller registration, AHC centre, and gold purity grade (e.g., 22K916).',
    category: 'Hallmarking',
    is_demo: false,
  },
  {
    question: 'What is the difference between ISI Mark (Scheme I) and CRS (Scheme II)?',
    answer: 'Scheme I (ISI Mark) involves comprehensive factory inspections, in-house laboratory audits, and sample testing for domestic industrial and consumer products (e.g. electrical appliances, cement, helmets, steel). Scheme II (CRS) is a self-declaration registration scheme based on testing at BIS recognized labs primarily for electronic and IT products (e.g. laptops, chargers, mobile phones).',
    category: 'Certification Schemes',
    is_demo: false,
  },
  {
    question: 'Is BIS certification mandatory for all products in India?',
    answer: 'BIS certification is mandatory for products covered under Quality Control Orders (QCOs) issued by Central Ministries (e.g. DPIIT, Ministry of Steel, MeitY). For non-QCO products, certification is voluntary.',
    category: 'Regulatory Compliance',
    is_demo: false,
  },
  {
    question: 'What concessions does BIS offer to MSMEs and Startups?',
    answer: 'BIS provides a 50% concession on application fee and marking fee for Micro enterprises, and a 20% concession for Small enterprises. Startups also receive expedited evaluation and fee benefits under the Startup India initiative.',
    category: 'MSME & Industry',
    is_demo: false,
  },
  {
    question: 'How do I report a fake or unauthorized ISI Mark on a product?',
    answer: 'You can lodge an immediate grievance via the official BIS Care Mobile App, email consumer@bis.gov.in, or submit a complaint on the BIS Consumer Portal with product photos and store invoices. BIS enforcement conducts raids and prosecutes offenders under the BIS Act 2016.',
    category: 'Consumer Protection',
    is_demo: false,
  },
  {
    question: 'How do testing laboratories obtain recognition under BIS LRS?',
    answer: 'Testing laboratories must hold ISO/IEC 17025 accreditation from NABL for the relevant Indian Standards. They apply on the BIS LIMS portal (limsbis.in), undergo a technical on-site audit by a BIS assessment team, and are integrated into the LIMS workflow upon approval.',
    category: 'Laboratories',
    is_demo: false,
  },
  {
    question: 'How can foreign manufacturers obtain BIS ISI certification?',
    answer: 'Foreign manufacturers apply under the Foreign Manufacturers Certification Scheme (FMCS — Scheme III). They must appoint an Authorized Indian Representative (AIR), host an on-site audit by BIS officers at their overseas plant, and submit samples for testing in India.',
    category: 'FMCS & Imports',
    is_demo: false,
  },
  {
    question: 'What are the 3 mandatory marks on hallmarked gold jewellery?',
    answer: 'Since July 2021, all hallmarked gold jewellery must bear exactly 3 marks: 1. BIS Triangular Logo, 2. Purity grade and fineness (e.g., 22K916, 18K750, 14K585), and 3. Unique 6-digit alphanumeric HUID code.',
    category: 'Hallmarking',
    is_demo: false,
  },
  {
    question: 'Where can I find the official text of an Indian Standard?',
    answer: 'Indian Standards can be searched, previewed, and purchased directly through the official BIS Portal at bis.gov.in or manakonline.in.',
    category: 'Standards Directory',
    is_demo: false,
  },
  {
    question: 'What penalties apply for manufacturing sub-standard goods under a mandatory QCO?',
    answer: 'Under Section 29 of the BIS Act 2016, manufacturing or selling goods in violation of mandatory QCOs is punishable with imprisonment up to 2 years, or a fine not less than Rs 2 Lakhs (which may extend up to 10 times the value of goods produced), or both.',
    category: 'Enforcement & Legal',
    is_demo: false,
  },
  {
    question: 'What is the validity period of a BIS CM/L licence?',
    answer: 'A BIS CM/L licence is initially granted for a period of not less than 1 year and up to 2 years, renewable upon payment of marking fees and demonstrated compliance during surveillance audits.',
    category: 'Product Certification',
    is_demo: false,
  },
  {
    question: 'Can a consumer get un-hallmarked gold jewellery tested for purity?',
    answer: 'Yes. Consumers can take their un-hallmarked gold jewellery to any BIS-recognized Assaying and Hallmarking Centre (AHC) for testing on payment of nominal testing fees.',
    category: 'Hallmarking',
    is_demo: false,
  },
  {
    question: 'What standard governs child toy safety in India?',
    answer: 'Safety of toys is governed by the IS 9873 series (Mechanical, Flammability, Heavy Metal Migration) and IS 15644 (Electric Toys). Certification under Scheme I (ISI Mark) is mandatory for all domestic manufacturers and importers.',
    category: 'Toy Safety',
    is_demo: false,
  },
  {
    question: 'What is Sevottam certification under IS 15700?',
    answer: 'IS 15700 is the Indian Standard for Service Quality Management Systems in Public Service Organizations. It certifies citizen charters, service delivery standards, and grievance redressal mechanisms.',
    category: 'Public Services',
    is_demo: false,
  },
  {
    question: 'How do I know if an electrical cable is safe for house wiring?',
    answer: 'Ensure the cable bears the ISI Mark with standard number IS 694, conductor cross-section (e.g. 1.5 sq mm / 2.5 sq mm), voltage rating (1100V), and a valid 7-digit CM/L licence number printed at regular intervals along the cable sheath.',
    category: 'Electrical Safety',
    is_demo: false,
  },
];

const scanRecordsData = [
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-8400012395',
    product_name: 'Pigeon Stainless Steel Electric Kettle 1.8L',
    extracted_information: {
      standard: 'IS 302 (Part 2/Sec 3): 2007',
      licenceNumber: 'CM/L-8400012395',
      brand: 'Pigeon',
      voltage: '230V AC - 50Hz - 1500W',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-8400012395',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'macro_huid_hallmark',
    scanned_value: 'K92A8M',
    product_name: '22K Gold Traditional Kada / Bangle',
    extracted_information: {
      standard: 'IS 1417: 2016',
      huid: 'K92A8M',
      purity: '22K (916)',
      jeweller: 'Tanishq (Titan Company Ltd)',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'K92A8M',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_crs_label',
    scanned_value: 'R-41009823',
    product_name: 'Apple 67W USB-C Power Adapter',
    extracted_information: {
      standard: 'IS 13252 (Part 1): 2010',
      regNumber: 'R-41009823',
      brand: 'Apple',
      model: 'A2518',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'R-41009823',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-0012890',
    product_name: 'Tata Tiscon 550D Super Ductile TMT Rebar 12mm',
    extracted_information: {
      standard: 'IS 1786: 2008',
      licenceNumber: 'CM/L-0012890',
      grade: 'Fe 550D',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-0012890',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-5100088921',
    product_name: 'Himalayan Natural Mineral Water 1L Bottle',
    extracted_information: {
      standard: 'IS 15410: 2003',
      licenceNumber: 'CM/L-5100088921',
      brand: 'Himalayan',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-5100088921',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-6100029311',
    product_name: 'Vega Crux Full Face ISI Certified Helmet (L)',
    extracted_information: {
      standard: 'IS 4151: 2020',
      licenceNumber: 'CM/L-6100029311',
      brand: 'Vega',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-6100029311',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-30004921',
    product_name: 'Polycab 2.5 sq mm Green FR PVC Wire 90m',
    extracted_information: {
      standard: 'IS 694: 2010',
      licenceNumber: 'CM/L-30004921',
      spec: '2.5 sq mm FR 1100V',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-30004921',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-8200192384',
    product_name: 'Anchor by Panasonic Roma 6A 3-Pin Socket',
    extracted_information: {
      standard: 'IS 1293: 2019',
      licenceNumber: 'CM/L-8200192384',
      rating: '6A 240V',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-8200192384',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-7300019283',
    product_name: 'Funskool Giggles Activity Stacker Toy for Toddlers',
    extracted_information: {
      standard: 'IS 9873 (Part 1): 2019',
      licenceNumber: 'CM/L-7300019283',
      brand: 'Funskool',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-7300019283',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_crs_label',
    scanned_value: 'R-41001294',
    product_name: 'Philips 9W B22 Cool Daylight LED Bulb',
    extracted_information: {
      standard: 'IS 16102 (Part 1): 2012',
      regNumber: 'R-41001294',
      brand: 'Philips',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'R-41001294',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-1100029381',
    product_name: 'UltraTech Super 53 Grade Ordinary Portland Cement 50kg',
    extracted_information: {
      standard: 'IS 269: 2015',
      licenceNumber: 'CM/L-1100029381',
      brand: 'UltraTech',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-1100029381',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_crs_label',
    scanned_value: 'R-41098231',
    product_name: 'Waaree 540W Mono PERC Solar PV Module',
    extracted_information: {
      standard: 'IS 14286 / IEC 61215: 2010',
      regNumber: 'R-41098231',
      brand: 'Waaree',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'R-41098231',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'macro_huid_hallmark',
    scanned_value: 'A78X4Y',
    product_name: '18K Diamond Studded Gold Ring',
    extracted_information: {
      standard: 'IS 1417: 2016',
      huid: 'A78X4Y',
      purity: '18K (750)',
      jeweller: 'Kalyan Jewellers India Ltd',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'A78X4Y',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'macro_huid_hallmark',
    scanned_value: 'B39W1Q',
    product_name: '24K Gold Minted Bullion Coin 10g',
    extracted_information: {
      standard: 'IS 1417: 2016',
      huid: 'B39W1Q',
      purity: '24K (999)',
      jeweller: 'MMTC-PAMP India Private Ltd',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'B39W1Q',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-7200045612',
    product_name: 'Havells Aqua Plus 1.2L Double Wall Kettle',
    extracted_information: {
      standard: 'IS 302 (Part 2/Sec 3): 2007',
      licenceNumber: 'CM/L-7200045612',
      brand: 'Havells',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-7200045612',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-9100038291',
    product_name: 'Prestige PKOSS 1.5L Electric Kettle',
    extracted_information: {
      standard: 'IS 302 (Part 2/Sec 3): 2007',
      licenceNumber: 'CM/L-9100038291',
      brand: 'Prestige',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-9100038291',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_crs_label',
    scanned_value: 'R-41012399',
    product_name: 'Samsung 25W Super Fast Wall Charger',
    extracted_information: {
      standard: 'IS 13252 (Part 1): 2010',
      regNumber: 'R-41012399',
      brand: 'Samsung',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'R-41012399',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_crs_label',
    scanned_value: 'R-41028711',
    product_name: 'Mi 33W SonicCharge 2.0 Fast Charger',
    extracted_information: {
      standard: 'IS 13252 (Part 1): 2010',
      regNumber: 'R-41028711',
      brand: 'Xiaomi',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'R-41028711',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'CM/L-0029811',
    product_name: 'JSW Neosteel 500D Fe TMT Rebar 16mm',
    extracted_information: {
      standard: 'IS 1786: 2008',
      licenceNumber: 'CM/L-0029811',
      brand: 'JSW Neosteel',
    },
    verification_status: 'VERIFIED',
    matched_record_id: 'CM/L-0029811',
    is_demo: false,
  },
  {
    user_id: 'consumer_demo_user',
    scan_type: 'camera_isi_label',
    scanned_value: 'INVALID-99999999',
    product_name: '[DEMO] Uncertified Road Side Ceramic Heater (Fake ISI Stamp Test)',
    extracted_information: {
      standard: 'IS 302 (Part 2/Sec 3): 2007',
      licenceNumber: 'INVALID-99999999',
      error: 'Unregistered licence number format',
    },
    verification_status: 'NOT VERIFIED',
    matched_record_id: null,
    is_demo: true,
  },
];

module.exports = {
  standardsData,
  documentsData,
  documentChunksData,
  productsData,
  hallmarkingData,
  laboratoriesData,
  bisServicesData,
  faqsData,
  scanRecordsData,
};
